name: Delete old BackstopJS preview pages
on:
  workflow_dispatch:
  schedule:
    - cron: '5 4 * * *'

concurrency:
  group: visual-regression

jobs:
  tests:
    uses: city-of-helsinki/drupal-gh-actions/.github/workflows/visual-regression-cleanup.yml
    with:
      repository: city-of-helsinki/helsinki-paatokset-visual-regression
